# Uygulama Adı
spring:
  application:
    name: e-commerce

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 909493653302-4291f26lubjrt7urqrhmks2ck5mnckm2.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
        provider:
          google:
            issuer-uri: https://accounts.google.com

  # http://localhost:8080/oauth2/authorization/google
  # Datasource Configuration (Veritabanı Bağlantısı)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecommerce}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  # JPA Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect



logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}


upload:
  dir: /var/www/upload/
  url: http://localhost:8080/
  file:
    url: http://localhost:8080/api/upload/